export const SCHEMA_SQL = [
  `CREATE TABLE IF NOT EXISTS "user" (
    id text PRIMARY KEY,
    name text NOT NULL,
    email text NOT NULL UNIQUE,
    email_verified boolean NOT NULL DEFAULT false,
    image text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    credit_micros bigint NOT NULL DEFAULT 0,
    default_model text DEFAULT 'nexus/auto',
    allow_training boolean NOT NULL DEFAULT false,
    zdr boolean NOT NULL DEFAULT false,
    log_prompts boolean NOT NULL DEFAULT false,
    auto_topup_enabled boolean NOT NULL DEFAULT false,
    auto_topup_threshold_usd numeric,
    auto_topup_amount_usd numeric,
    stripe_customer_id text
  )`,
  `ALTER TABLE "user" ADD COLUMN IF NOT EXISTS stripe_customer_id text`,
  `CREATE TABLE IF NOT EXISTS "session" (
    id text PRIMARY KEY,
    expires_at timestamp NOT NULL,
    token text NOT NULL UNIQUE,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now(),
    ip_address text,
    user_agent text,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS session_user_idx ON "session"(user_id)`,
  `CREATE TABLE IF NOT EXISTS "account" (
    id text PRIMARY KEY,
    account_id text NOT NULL,
    provider_id text NOT NULL,
    issuer text NOT NULL DEFAULT '',
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    access_token text,
    refresh_token text,
    id_token text,
    access_token_expires_at timestamp,
    refresh_token_expires_at timestamp,
    scope text,
    password text,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS account_user_idx ON "account"(user_id)`,
  `ALTER TABLE "account" ADD COLUMN IF NOT EXISTS issuer text NOT NULL DEFAULT ''`,
  `CREATE TABLE IF NOT EXISTS "verification" (
    id text PRIMARY KEY,
    identifier text NOT NULL,
    value text NOT NULL,
    expires_at timestamp NOT NULL,
    created_at timestamp DEFAULT now(),
    updated_at timestamp DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS "organization" (
    id text PRIMARY KEY,
    name text NOT NULL,
    slug text NOT NULL UNIQUE,
    owner_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS "organization_member" (
    id text PRIMARY KEY,
    organization_id text NOT NULL REFERENCES "organization"(id) ON DELETE CASCADE,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    role text NOT NULL DEFAULT 'member',
    created_at timestamp NOT NULL DEFAULT now(),
    UNIQUE (organization_id, user_id)
  )`,
  `CREATE TABLE IF NOT EXISTS "workspace" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    organization_id text REFERENCES "organization"(id) ON DELETE SET NULL,
    name text NOT NULL,
    slug text NOT NULL,
    is_default boolean NOT NULL DEFAULT false,
    include_byok_in_budgets boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL DEFAULT now(),
    UNIQUE (user_id, slug)
  )`,
  `CREATE TABLE IF NOT EXISTS "workspace_budget" (
    id text PRIMARY KEY,
    workspace_id text NOT NULL REFERENCES "workspace"(id) ON DELETE CASCADE,
    interval text NOT NULL,
    limit_micros bigint NOT NULL,
    spent_micros bigint NOT NULL DEFAULT 0,
    UNIQUE (workspace_id, interval)
  )`,
  `CREATE TABLE IF NOT EXISTS "api_key" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    workspace_id text REFERENCES "workspace"(id) ON DELETE SET NULL,
    name text NOT NULL,
    key_hash text NOT NULL UNIQUE,
    key_prefix text NOT NULL,
    is_management boolean NOT NULL DEFAULT false,
    disabled boolean NOT NULL DEFAULT false,
    limit_micros bigint,
    usage_micros bigint NOT NULL DEFAULT 0,
    limit_reset text,
    include_byok_in_limit boolean NOT NULL DEFAULT false,
    last_used_at timestamp,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS api_key_user_idx ON "api_key"(user_id)`,
  `CREATE TABLE IF NOT EXISTS "credit_ledger" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    type text NOT NULL,
    micros bigint NOT NULL,
    stripe_session_id text,
    generation_id text,
    note text,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS ledger_user_idx ON "credit_ledger"(user_id)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS ledger_stripe_session_uidx ON "credit_ledger"(stripe_session_id)`,
  `CREATE TABLE IF NOT EXISTS "generation" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    api_key_id text REFERENCES "api_key"(id) ON DELETE SET NULL,
    workspace_id text,
    requested_model text NOT NULL,
    routed_model text NOT NULL,
    provider text NOT NULL,
    finish_reason text,
    prompt_tokens integer NOT NULL DEFAULT 0,
    completion_tokens integer NOT NULL DEFAULT 0,
    reasoning_tokens integer NOT NULL DEFAULT 0,
    cost_micros bigint NOT NULL DEFAULT 0,
    latency_ms integer,
    streamed boolean NOT NULL DEFAULT false,
    is_byok boolean NOT NULL DEFAULT false,
    app_referer text,
    app_title text,
    prompt text,
    completion text,
    error text,
    metadata jsonb,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS generation_user_idx ON "generation"(user_id)`,
  `CREATE INDEX IF NOT EXISTS generation_created_idx ON "generation"(created_at)`,
  `CREATE TABLE IF NOT EXISTS "byok_credential" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    workspace_id text,
    provider text NOT NULL,
    encrypted_key text NOT NULL,
    label text,
    deleted boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS "guardrail" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    workspace_id text,
    name text NOT NULL,
    allowed_models jsonb,
    blocked_models jsonb,
    max_cost_micros bigint,
    prompt_injection boolean NOT NULL DEFAULT false,
    sensitive_info boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS "file" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    workspace_id text,
    filename text NOT NULL,
    mime text NOT NULL,
    size integer NOT NULL,
    content text,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS "preset" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    slug text NOT NULL,
    version integer NOT NULL DEFAULT 1,
    config jsonb NOT NULL,
    created_at timestamp NOT NULL DEFAULT now(),
    updated_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS "oauth_code" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    code_hash text NOT NULL,
    code_challenge text NOT NULL,
    expires_at timestamp NOT NULL,
    used boolean NOT NULL DEFAULT false
  )`,
  `CREATE TABLE IF NOT EXISTS "provider_health" (
    id text PRIMARY KEY,
    provider text NOT NULL UNIQUE,
    status text NOT NULL DEFAULT 'unknown',
    latency_ms integer,
    last_check timestamp NOT NULL DEFAULT now(),
    detail text
  )`,
  `CREATE TABLE IF NOT EXISTS "catalog_snapshot" (
    id text PRIMARY KEY,
    source text NOT NULL,
    model_count integer NOT NULL,
    fetched_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS "video_job" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    model text NOT NULL,
    prompt text NOT NULL,
    status text NOT NULL DEFAULT 'queued',
    result_url text,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS "observability_destination" (
    id text PRIMARY KEY,
    user_id text NOT NULL REFERENCES "user"(id) ON DELETE CASCADE,
    workspace_id text,
    type text NOT NULL,
    name text NOT NULL,
    config jsonb NOT NULL,
    deleted boolean NOT NULL DEFAULT false,
    created_at timestamp NOT NULL DEFAULT now()
  )`,
];
