/**
 * Regenerates packages/sdk/src/model-ids.ts from the live catalog.
 * Usage: npx tsx scripts/sync-sdk-models.ts
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { allModels } from "../src/lib/catalog";

const ids = allModels()
  .map((m) => m.id)
  .sort((a, b) => a.localeCompare(b));

const body = `/** Auto-generated by scripts/sync-sdk-models.ts — do not edit by hand. */
export const NEXUS_MODEL_IDS = [
${ids.map((id) => `  ${JSON.stringify(id)},`).join("\n")}
] as const;

export type NexusModelId = (typeof NEXUS_MODEL_IDS)[number] | (string & {});
`;

const out = join(process.cwd(), "packages/sdk/src/model-ids.ts");
writeFileSync(out, body);
console.log(`Wrote ${ids.length} model ids → ${out}`);
